version: "3"

services:

  database:
    image: "postgres:11"
    environment:
      POSTGRES_USER: ${OMERO_DB_USER}
      POSTGRES_DB: ${OMERO_DB_NAME}
      POSTGRES_PASSWORD: ${OMERO_DB_PASS}
    hostname: ${OMERO_DB_HOST}
    networks:
      - omero_net
    volumes:
      - "database:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${OMERO_DB_USER} -d postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

  omeroserver:
    image: "openmicroscopy/omero-server:5"
    environment:
      CONFIG_omero_db_host: ${OMERO_DB_HOST}
      CONFIG_omero_db_user: ${OMERO_DB_USER}
      CONFIG_omero_db_pass: ${OMERO_DB_PASS}
      CONFIG_omero_db_name: ${OMERO_DB_NAME}
      ROOTPASS: ${OMERO_ROOT_PASS}
      CONFIG_omero_client_icetransports: ssl,wss,ws
      CONFIG_omero_glacier2_IceSSL_Ciphers: ADH:HIGH
      # CONFIG_omero_glacier2_IceSSL_DefaultDir: /etc/ssl/selfsigned
      # CONFIG_omero_glacier2_IceSSL_CAs: cacert.pem
      # CONFIG_omero_glacier2_IceSSL_CertFile: server.p12
      # CONFIG_omero_glacier2_IceSSL_Password: secret
    depends_on:
      database:
        condition: service_healthy
    networks:
      - omero_net
    ports:
      - "${APP_API_PORT}:4063"
      - "${APP_API_SSL_PORT}:4064"
      - "${WEBSOCK_PORT}:4065"
      - "${WEBSOCK_SSL_PORT}:4066"
    expose:
      - 4064
    healthcheck:
      test: "curl -f https://localhost:4064 --insecure"
      interval: 3s
      timeout: 5s
      retries: 20
    volumes:
      - "omero:/OMERO"

  omeroweb:
    # This container uses the tag for the latest web release of OMERO 5
    # To upgrade to the next major release, increment the major version number
    image: "openmicroscopy/omero-web-standalone:5"
    environment:
      OMEROHOST: omeroserver
      #CONFIG_omero_web_server__list: '[["omeroserver", 4064, "omeroserver"], ["fool.com", 4064, "test"]]'
      ROOTPASS: ${OMERO_ROOT_PASS}
      CONFIG_omero_web_redirect__allowed__hosts: ${OMERO_WEB_ALLOWED_HOST}
      CONFIG_omero_web_debug: ${OMERO_WEB_DEBUG}
      CONFIG_omero_web_secure__proxy__ssl__header: ${OMERO_WEB_SECURE__PROXY__SSL__HEADER}
      CONFIG_omero_web_secure: True
      CONFIG_omero_web_api_absolute__url: ${OMERO_WEB_ABSOLUT_URL}
      CONFIG_omero_web_public_enabled: ${OMERO_WEB_PUBLIC_ENABLE}
      CONFIG_omero_web_public_user: ${OMERO_WEB_PUBLIC_USER}
      CONFIG_omero_web_public_password: ${OMERO_WEB_PUBLIC_PASSWORD}
      CONFIG_omero_web_public_server_id: 1
      CONFIG_omero_web_public_url__filter: '^/(webadmin/myphoto/|webclient/(?!(script_ui|ome_tiff|figure_script))|webgateway/(?!(archived_files|download_as))|iviewer|api)'
    depends_on:
     omeroserver: 
        condition: service_healthy
    networks:
      - omero_net
    ports:
      - "${APP_PORT}:4080"
    volumes:
      - ./91-add-public-user.sh:/startup/91-add-public-user.sh
    restart: always
    healthcheck:
      test: "curl -f http://localhost:4080"
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  omero_net:
    name: omero_net

volumes:
  database:
  omero:
